sudo: required
services:
  - docker

env:
    global:
        - DOCKER_VERSION=17.05.0~ce-0~ubuntu-trusty

before_install:
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
  - docker version

script:
  - make test